In [1]:
import torch
from sklearn.preprocessing import StandardScaler

import dataset
import models

import pytorch_lightning as pl

from torch.utils.data import DataLoader


In [2]:
train = dataset.PickleTraceDataset('./data/DPO4032_10_211102-181109.pkl', trace_size=35000, scaler=StandardScaler())
test = dataset.PickleTraceDataset('./data/DPO4032_10_211103-161117.pkl', trace_size=35000, scaler=StandardScaler())
train_loader = DataLoader(train, batch_size=64, shuffle=True)
test_loader = DataLoader(test, batch_size=64, shuffle=True)

In [3]:
net = models.CNNModel(learning_rate=2e-4, weight_decay=5e-3)

In [4]:
trainer = pl.Trainer(max_epochs=15, gpus=1)
trainer.fit(net, train_loader, test_loader)


GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name        | Type             | Params
-------------------------------------------------
0 | criterion   | CrossEntropyLoss | 0     
1 | sparse_conv | Sequential       | 71    
2 | dense_conv  | Sequential       | 201   
3 | fc          | Sequential       | 6.6 M 
-------------------------------------------------
6.6 M     Trainable params
0         Non-trainable params
6.6 M     Total params
26.221    Total estimated model params size (MB)


C:\Users\TecGun\anaconda3\envs\CPA\lib\site-packages\pytorch_lightning\trainer\data_loading.py:376: UserWarning: Your val_dataloader has `shuffle=True`, it is best practice to turn this off for val/test/predict dataloaders.
  rank_zero_warn(
C:\Users\TecGun\anaconda3\envs\CPA\lib\site-packages\pytorch_lightning\trainer\data_loading.py:105: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 4 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\TecGun\anaconda3\envs\CPA\lib\site-packages\deprecate\deprecation.py:115: LightningDeprecationWarning: The `accuracy` was deprecated since v1.3.0 in favor of `torchmetrics.functional.classification.accuracy.accuracy`. It will be removed in v1.5.0.
  stream(template_mgs % msg_args)
C:\Users\TecGun\anaconda3\envs\CPA\lib\site-packages\pytorch_lightning\trainer\data_lo

C:\Users\TecGun\anaconda3\envs\CPA\lib\site-packages\pytorch_lightning\trainer\connectors\logger_connector\result.py:405: LightningDeprecationWarning: One of the returned values {'log', 'correct', 'total'} has a `grad_fn`. We will detach it automatically but this behaviour will change in v1.6. Please detach it manually: `return {'loss': ..., 'something': something.detach()}`
  warning_cache.deprecation(


C:\Users\TecGun\anaconda3\envs\CPA\lib\site-packages\pytorch_lightning\trainer\trainer.py:1051: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")


In [23]:
for _ in range(10):
    feat = next(iter(train_loader))

    res = net.forward(feat[0])
    print(accuracy(res, feat[1]))
    print(torch.argmax(res, dim=1))
    print(feat[1])


tensor(0.4219)
tensor([224, 243, 208, 158, 208, 110, 223, 223,  35, 132, 251, 153,   7, 177,
        229, 243,  99, 102,  53, 178, 208,  56, 213, 217, 218, 147, 156,  11,
        248, 249,  63, 238, 183, 131, 253,  80, 227, 139,  78, 171,  13, 231,
        212,  96,   4, 218, 216, 160, 235, 193, 161,  67, 230,  98, 222, 162,
        107, 106, 252, 230,  59, 125,  26, 122])
tensor([194, 230,  76, 112, 155, 110, 113, 214,  42, 109, 251, 153,   7, 177,
        229, 205,  99, 102,  63, 163, 232,  38, 213, 217, 162, 147,  39, 143,
         75,  24, 243, 238, 183, 145,  28,  80, 227, 139,   7, 171, 138, 239,
        212,  96, 172,  67, 216, 226, 134, 193,  71,  67, 128,  98, 222, 162,
        107,  89,  30, 127,  57, 119,  26, 148])
tensor(0.4531)
tensor([185,   2, 228,  36,  96,   8,  21, 110,  61, 198, 108, 105, 156,  22,
        156, 227, 214,  45,  87, 165,  50, 242, 136, 218, 209, 100,  28,  18,
        135,  68,  96,  33, 133, 229,  13, 153,  50, 239,   3, 247, 185, 146,
         52,  

In [10]:
from pytorch_lightning.metrics.functional import accuracy
accuracy(res, feat[1])

NameError: name 'output' is not defined

In [28]:
print(res.shape)
print(feat[1].shape)

torch.Size([32, 256])
torch.Size([32])


In [5]:
feat[1].type()

'torch.LongTensor'

'torch.LongTensor'